FROM node:20-alpine

WORKDIR /app

# Instalar dependencias
COPY src/frontend/package*.json ./
RUN npm install

# Copiar el código fuente
COPY src/frontend/ .

# Exponer el puerto que usa Next.js
EXPOSE 3000

# Next.js necesita este flag para ejecutarse en un contenedor Docker
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV development

# Ejecutar el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]