FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
COPY src/backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
COPY src/backend/ .

# Exponer el puerto que usa Flask
EXPOSE 5000

# Ejecutar la aplicación escuchando en todas las interfaces
CMD ["python", "run.py"]
