"""Add last_name to users

Revision ID: 02644fa8bb55
Revises: 834f79aef443
Create Date: 2025-05-27 10:24:27.626725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02644fa8bb55'
down_revision = '834f79aef443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
