# Migración de base de datos: creación de la tabla users
# Define la estructura inicial de la tabla de usuarios con campos para autenticación
# Incluye restricciones de unicidad para username y email

"""Corrección de nombre de tabla users

Revision ID: 72c144c63040
Revises: 2404c81b8c0d
Create Date: 2025-02-26 00:41:40.620655

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "72c144c63040"
down_revision = "2404c81b8c0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
