"""Add created_at field

Revision ID: b15e74568949
Revises: 72c144c63040
Create Date: 2025-03-02 16:51:24.419360

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b15e74568949"
down_revision = "72c144c63040"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
